# Generated by Django 5.0.3 on 2024-08-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category_id',
            new_name='category_id',
        ),
    ]
